version: "3.7"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
  web:
    build: .
    restart: always
    command: uvicorn djchat.asgi:application --host 0.0.0.0
    environment:
      - ALLOWED_HOSTS=0.0.0.0
      - SECRET_KEY
      - POSTGRES_PASSWORD
      - DB_HOST=db
      - DB_ENGINE=django.db.backends.postgresql
      - DEBUG=False
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

volumes:
  db: null
